pipeline {
    agent any

    stages {

        stage('Check Python') {
            steps {
                sh '
                 sudo apt update
                 sudo apt install python3 python3-venv python3-pip -y
                    python3 --version 
                    pip3 --version 
                '
            }
        }

        stage('Setup Virtual Environment') {
            steps {
                sh '
                    python3 -m venv venv
                    . venv/bin/activate

                    pip install --upgrade pip
                    if [ -f "requirements.txt" ]; then
                        pip install -r requirements.txt
                    fi
                '
            }
        }

        stage('Lint') {
            steps {
                sh '
                    . venv/bin/activate
                    pip install flake8

                    # Run lint only, do not fail pipeline
                    flake8 || true
                '
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    . venv/bin/activate

                    # Run python tests if test folder exists
                    if [ -d "tests" ]; then
                        echo "Running tests..."
                        pytest -q || true
                    else
                        echo "No tests directory found. Skipping tests."
                    fi
                '''
            }
        }

        stage('Run Application') {
            when {
                expression { fileExists('app.py') }
            }
            steps {
                sh '''
                    . venv/bin/activate
                    echo "Running Python application..."
                    python app.py || true
                '''
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
